export const EVENT = {
  UPDATE_ISSUED_ALERTS: 'UPDATE_ISSUED_ALERTS',
  UPDATE_THUNDERSTORM_OUTLOOK: 'UPDATE_THUNDERSTORM_OUTLOOK',
  GENERATE_THUNDERSTORM_OUTLOOK_SUMMARY:
    'GENERATE_THUNDERSTORM_OUTLOOK_SUMMARY',
  UPDATE_SEVERE_WEATHER_OUTLOOK: 'UPDATE_SEVERE_WEATHER_OUTLOOK',
  GENERATE_SEVERE_WEATHER_OUTLOOK_SUMMARY:
    'GENERATE_SEVERE_WEATHER_OUTLOOK_SUMMARY',
};

export const NHISCHANNEL_EVENTS = {
  AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATING:
    'AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATING',
  AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATING:
    'AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATING',
  AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATED:
    'AI_THUNDERSTORM_OUTLOOK_SUMMARY_GENERATED',
  AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATED:
    'AI_SEVERE_WEATHER_OUTLOOK_SUMMARY_GENERATED',
  ISSUED_ALERTS_UPDATING: 'ISSUED_ALERTS_UPDATING',
  SEVERE_WEATHER_OUTLOOK_UPDATING: 'SEVERE_WEATHER_OUTLOOK_UPDATING',
  THUNDERSTORM_OUTLOOK_UPDATING: 'THUNDERSTORM_OUTLOOK_UPDATING',
  ISSUED_ALERTS_UPDATED: 'ISSUED_ALERTS_UPDATED',
  SEVERE_WEATHER_OUTLOOK_UPDATED: 'SEVERE_WEATHER_OUTLOOK_UPDATED',
  THUNDERSTORM_OUTLOOK_UPDATED: 'THUNDERSTORM_OUTLOOK_UPDATED',
};
